
#turbo 5

#include IP_Macro_Actions.inc
#include IP_Macro_Auto.inc
#include IP_Macro_Commands.inc
#include IP_Macro_Events.inc
#include IP_Macro_Setup.inc

sub Main() {

	/call "Setup"
	/call "Setup_Auto"

	/echo IP loaded.

	:Main

	/call "Check_Actions"
	/call "Check_Events"
	/call "Check_Auto"
	
	/goto :Main

	/return
}


|Add auto-assist
|Add netfollow
|Fix ranged assist
|Add unstuck to auto
|Add debuffs
|Add resist check for non-detrimental
|Add timers for debuffs